artifact_location: file:///C:/Users/onyiu/Documents/GitHub/Retail_Demand_Forcast/mlflow_results2/431536349637880659
creation_time: 1755743555334
experiment_id: '431536349637880659'
last_update_time: 1755743555334
lifecycle_stage: active
name: xgboost_favorita
